on: 
  push:
    branches:
      - master

name: ?? Deploy website on push
jobs:
  web-deploy:
    name: ?? Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ?? Get latest code
      uses: actions/checkout@v2
    
    - name: ?? Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        server-dir: public_html/projeto-landing-page-com-boostrap/